name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Hetzner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "Conectado correctamente. Iniciando despliegue..."

            # Entrar en la carpeta del proyecto
            cd ~/projecte-final-2025-26-daw-adsum_grup4

            # Resetear cualquier cambio local y traer lo nuevo
            git fetch origin main
            git reset --hard origin/main

            # Reconstruir contenedores usando el archivo .env.production
            docker compose --env-file .env.production -f docker-compose.prod.yml up -d --build

            # Limpiar
            docker system prune -f
            echo "Despliegue finalizado con éxito."
